# name: Authenticate to GCP via WIF
# on:
#   workflow_call:
#     inputs:
#       workload_identity_provider:
#         required: true
#         type: string
#       service_account:
#         required: true
#         type: string

#     outputs:
#       credentials_file_path:
#         description: "Path to GCP credentials file"
#         value: ${{ jobs.auth.outputs.credentials_file_path }}

# jobs:
#   auth:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       id-token: write

#     outputs:
#       credentials_file_path: ${{ steps.auth.outputs.credentials_file_path }}

#     steps:
#     - name: Authenticate to GCP
#       id: auth
#       uses: google-github-actions/auth@v2
#       with:
#         create_credentials_file: true
#         workload_identity_provider: ${{ inputs.workload_identity_provider }}
#         service_account: ${{ inputs.service_account }}

#     - name: Export credentials path
#       run: echo "GOOGLE_APPLICATION_CREDENTIALS=${{ steps.auth.outputs.credentials_file_path }}" >> $GITHUB_ENV
