name: Authenticate to GCP

on:
  workflow_call:
    inputs:
      workload_identity_provider:
        required: true
        type: string
      service_account:
        required: true
        type: string
      project_id:
        required: true
        type: string

jobs:
  auth:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    
      - name: Authenticate via WIF
        id: auth
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ inputs.workload_identity_provider }}
          service_account: ${{ inputs.service_account }}
