name: Authenticate to GCP

on:
  workflow_call:
    inputs:
      workload_identity_provider:
        required: true
        type: string
      service_account:
        required: true
        type: string
      project_id:
        required: true
        type: string
    outputs:
      credentials_json_b64:
        description: "Base64-encoded credentials file"
        value: ${{ jobs.auth.outputs.credentials_json_b64 }}


jobs:
  auth:
    runs-on: ubuntu-latest

    outputs:
      credentials_json_b64: ${{ steps.encode.outputs.credentials_json_b64 }}

    steps:

      - name: Authenticate via WIF
        id: auth
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ inputs.workload_identity_provider }}
          service_account: ${{ inputs.service_account }}

      - name: Base64 encode credentials
        id: encode
        run: |
          echo "credentials_json_b64=$(base64 ${{ steps.auth.outputs.credentials_file_path }} | tr -d '\n')" >> $GITHUB_OUTPUT