name: Main Terraform WIF Workflow

on:
  push:
    branches: [main]

env:
  RESOURCE_NAME: "gcs"
  REGION: "usc1"
  TERRAFORM_VERSION: "1.8.5"

jobs:
  auth:
    uses: ./.github/workflows/auth-reusable.yaml
    with:
      workload_identity_provider: 'projects/349782046408/locations/global/workloadIdentityPools/github-demo-pool/providers/github-identity-provider'
      service_account: 'sa-workload-identity-fed@prj-gcp-inframod-01.iam.gserviceaccount.com'
      project_id: 'prj-gcp-inframod-01'

  terraform:
    needs: auth
    uses: ./.github/workflows/terraform-reusable.yaml
    with:
      resource_name: ${{ env.RESOURCE_NAME }}
      region: ${{ env.REGION }}
      terraform_version: ${{ env.TERRAFORM_VERSION }}
