name: Main Terraform WIF Workflow

on:
  push:
    branches: [main]

jobs:

  auth:
    uses: ./.github/workflows/auth.yaml
    with:
      workload_identity_provider: 'projects/349782046408/locations/global/workloadIdentityPools/github-demo-pool/providers/github-identity-provider'
      service_account: 'sa-workload-identity-fed@prj-gcp-inframod-01.iam.gserviceaccount.com'
      project_id: 'prj-gcp-inframod-01'

  terraform:
    needs: auth
    uses: ./.github/workflows/terraform.yaml
    with:
      resource_name: 'gcs'
      region: 'usc1'
      terraform_version: '1.8.5'
