name: Terraform Deploy

on:
  workflow_call:
    inputs:
      resource_name:
        required: true
        type: string
      region:
        required: true
        type: string
      terraform_version:
        required: false
        default: "1.8.5"
        type: string
      credentials_json_b64:
        required: true
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: Write GCP credentials to file
        run: |
          echo "${{ inputs.credentials_json_b64 }}" | base64 -d > "$HOME/adc.json"
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/adc.json" >> $GITHUB_ENV
          
      - name: Terraform Init
        run: |
          terraform init -backend-config=${{ github.workspace }}/Modules/${{ inputs.resource_name }}/config/backend/${{ inputs.region }}/backend.auto.tfvars
        working-directory: Modules/${{ inputs.resource_name }}/config

      - name: Terraform Plan
        run: |
          terraform plan -var-file=${{ github.workspace }}/Modules/${{ inputs.resource_name }}/${{ inputs.region }}/terraform.tfvars -out=tfplan
        working-directory: Modules/${{ inputs.resource_name }}/config

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: Modules/${{ inputs.resource_name }}/config
