name: Terraform Dispatcher

on:
  push:
    branches:
      - feature/development 
  pull_request:
    paths:
      - 'Modules/**'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      gcs: ${{ steps.filter.outputs.gcs1 }}
      vm: ${{ steps.filter.outputs.gcs2 }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Filter changed paths
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            gcs1:
              - 'Modules/gcs1/**'
            gcs2:
              - 'Modules/gcs2/**'

  plan-gcs:
    needs: detect-changes
    if: needs.detect-changes.outputs.gcs1 == 'true'
    uses: ./.github/workflows/terraform-plan-pr.yaml
    with:
      workload_identity_provider: 'projects/349782046408/locations/global/workloadIdentityPools/github-demo-pool/providers/github-identity-provider'
      service_account: 'sa-workload-identity-fed@prj-gcp-inframod-01.iam.gserviceaccount.com'
      project_id: 'prj-gcp-inframod-01'
      resource_name: 'gcs1'
      region: 'usc1'

  plan-vm:
    needs: detect-changes
    if: needs.detect-changes.outputs.gcs2 == 'true'
    uses: ./.github/workflows/terraform-plan-pr.yaml
    with:
      workload_identity_provider: 'projects/349782046408/locations/global/workloadIdentityPools/github-demo-pool/providers/github-identity-provider'
      service_account: 'sa-workload-identity-fed@prj-gcp-inframod-01.iam.gserviceaccount.com'
      project_id: 'prj-gcp-inframod-01'
      resource_name: 'gcs2'
      region: 'usc1'